// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackNStock.Api.Data;

#nullable disable

namespace TrackNStock.Api.Migrations
{
    [DbContext(typeof(TrackNStockDbContext))]
    [Migration("20251120004007_Updated the Pproduct model.")]
    partial class UpdatedthePproductmodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackNStock.Api.Models.DomainModel.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShopOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShopOwnerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 7701,
                            OrderDate = new DateTime(2025, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 8801,
                            Quantity = 1,
                            ShopOwnerId = 9901,
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("TrackNStock.Api.Models.DomainModel.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoughtPrice")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Sold")
                        .HasColumnType("bit");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 8801,
                            BoughtPrice = 100,
                            Name = "Product Name Demo",
                            Quantity = 1,
                            Sold = false,
                            UnitPrice = 110m
                        });
                });

            modelBuilder.Entity("TrackNStock.Api.Models.DomainModel.Sales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("SalesDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 6601,
                            OrderId = 7701,
                            Quantity = 1,
                            SalesDate = new DateTime(2025, 10, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            UnitPrice = 110
                        });
                });

            modelBuilder.Entity("TrackNStock.Api.Models.DomainModel.ShopOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShopOwners");

                    b.HasData(
                        new
                        {
                            Id = 9901,
                            Location = "Location Demo",
                            OwnerName = "Owner Name Demo",
                            PhoneNumber = "Phone Number Demo",
                            ShopName = "Shop Name Demo"
                        });
                });

            modelBuilder.Entity("TrackNStock.Api.Models.DomainModel.Order", b =>
                {
                    b.HasOne("TrackNStock.Api.Models.DomainModel.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackNStock.Api.Models.DomainModel.ShopOwner", "ShopOwner")
                        .WithMany()
                        .HasForeignKey("ShopOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShopOwner");
                });

            modelBuilder.Entity("TrackNStock.Api.Models.DomainModel.Sales", b =>
                {
                    b.HasOne("TrackNStock.Api.Models.DomainModel.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
